### ISSUE TITLE
browser-sign-in readme does not match console defaults

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/samples-ios#22]
I'm trying to build these samples locally for the first time. I think some of these issues apply to both samples, but I'm going to speak to `browser-sign-in` here.

The readme says:
> you will need the following:
> - An Okta Application, configured for Web mode.

But it also links to https://developer.okta.com/quickstart/#/ios/nodejs/express, which says to 
> Choose Native app as the platform

I will trust the readme and create `Web`.

The readme says:
> You need to gather the following information from the Okta Developer Console:
> - Client ID, Redirect URI, Logout redirect URI

The application I created in Okta does not have a Logout redirect URI. I don't know what it should be.

The readme says I need to set a URL scheme:
> For example, if your Redirect URI is com.okta.example:/callback, the URL Scheme will be com.okta.example.

My Redirect URI does not look like that. The readme said to "use the default properties", and the default Redirect URI is `http://localhost:8080/authorization-code/callback`.

- Should the readme have instructed me to create a `Native` application?
- Should the readme instruct me to create a Logout redirect URI?

**Comment by anastasiiaiurok-okta** [comment]
@alexdahl-okta Changed README to instruct user to create a Native application. Correspondent instruction contains details on creating logout redirect URL.
