### ISSUE TITLE
Cannot build due to incorrect Pods paths

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/samples-ios#23]
I'm trying to build both samples locally for the first time.

I have:

1. Cloned the repo according to readme instructions.
2. Installed CocoaPods via their Mac app.
3. Run `pod install`.
4. Opened the `*.xcworkspace` files as instructed by CocoaPods.
5. Edited `*.plist` files.
6. Clicked the build and run button.

When building either sample, the build fails and complains about Pods files. There are four errors with the same message:
```
/Users/alexdahl/Documents/Repository/samples-ios/browser-sign-in/Pods/Pods/Target Support Files/Pods-OktaBrowserSignIn/Pods-OktaBrowserSignIn.debug.xcconfig: unable to open file (in target "OktaBrowserSignIn" in project "OktaBrowserSignIn") (in target 'OktaBrowserSignIn')
```

I'm guessing the issue is that `/Pods` is duplicated in that path.
`samples-ios/browser-sign-in/Pods/Pods/Target Support Files/` does not exist.
`samples-ios/browser-sign-in/Pods/Target Support Files/` does exist.

I don't know where that path is defined, so I'm not sure how to investigate further.

macOS 10.13.6
Xcode 10.1 (10B61)
CocoaPods 1.5.2

**Comment by anastasiiaiurok-okta** [comment]
@alexdahl-okta Thanks for report. Please, check out updated repo and let us know whether there is any issue.

**Comment by alexdahl-okta** [comment]
@anastasiiaiurok-okta thanks, looks like it's fixed! The app builds and communicates with Okta successfully.
