### ISSUE TITLE
OktaOidcMetadataDiscovery.run() doesn't surface errors generated by OIDServiceDiscovery initializer

### ISSUE THREAD

**Issue by jrtibbetts** [okta/samples-ios#57]
When `OktaOidcMetadataDiscovery.run()` creates an `OIDServiceDiscovery` object from the `oktaAPI.get()` call, it doesn't pass in an `Error` pointer to get the specific error, so it just calls `callback()` with a generic `parseFailure`, which isn't very helpful. When I stepped into the `OIDServiceDiscovery` initializer in the debugger, I found that my problem was simply a missing `issuer` field in the plist, but it would have taken me far less time to find that if the error had been propagated up.

**Comment by IldarAbdullin-okta** [comment]
Thanks for submitting this issue, @jrtibbetts . It is very good point, I would expect that OIDC returns error much earlier, during instantiation of OIDC object.

Could you submit this issue in the main project repo - https://github.com/okta/okta-oidc-ios?

**Comment by jrtibbetts** [comment]
Sure.

**Comment by jrtibbetts** [comment]
Posted to https://github.com/okta/okta-oidc-ios/issues/168.

**Comment by IldarAbdullin-okta** [comment]
Thanks!
