### ISSUE TITLE
 Make iOS Quickstart code snippets compatible with Swift 4

### ISSUE THREAD

**Issue by jrtibbetts** [okta/samples-ios#59]
The code snippet in the iOS Quickstart guide's ["Implement Okta Sign-In"](https://developer.okta.com/quickstart/#implement-okta-sign-in) section use deprecated calls. The snippet

```
func application(_ app: UIApplication,
    open url: URL,
    options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {
  return OktaAuth.resume(url: url, options: options)
}
```

should be 

```
func application(_ app: UIApplication,
    open url: URL,
    options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
  return OktaAuth.resume(url, options: options)
}
```

Note the `.` in the options key, and the removal of the `url:` argument label in your own `OktaAuth.resume()` call.

**Comment by IldarAbdullin-okta** [comment]
Thanks for that note, @jrtibbetts . The whole documentation page is outdated and targeted library with version 0.1. We are actively working on documentation, so please expect updates soon
