### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by adamlatitude** [okta/samples-ios#69]
Immediately after clone: 

[!] CocoaPods could not find compatible versions for pod "OktaAuthSdk":
  In Podfile:
    OktaAuthSdk (= 2.0.0)

Suggest you add requirement for "pod repo update" in the docs for an easier user experience.

**Comment by IldarAbdullin-okta** [comment]
@adamlatitude , so `pod repo update` before `pod install` resolved your issue?

**Comment by adamlatitude** [comment]
Right. I don't use pods often so it's not a thing you know the first time you do it. Asking people to update in the Quickstart docs would make your sample a little smoother.
________________________________

**Comment by IldarAbdullin-okta** [comment]
Make sense. Will add a note in readme file. Thanks!

**Comment by IldarAbdullin-okta** [comment]
Added `pod repo update` to the readme file
