### ISSUE TITLE
unable to use test credentials

### ISSUE THREAD

**Issue by karthikNaga6232** [okta/samples-ios#70]
I was able to build it . after opening the app it shows Unauthenticated and Hangs

**Comment by IldarAbdullin-okta** [comment]
I suppose you use `Native-Sign-In` sample application. There is no code in it that could cause freeze. Did you set your `Okta org url` in the code? If not, this could be the cause of the exception

**Comment by karthikNaga6232** [comment]
My account got locked. I unlocked it and tried it and it worked . Do you have a process that works with SSO ?

**Comment by IldarAbdullin-okta** [comment]
With Native sign-in flow SSO is application's concern. You can store access token in the keychain and share stored record with your applications that are in the same app group

**Comment by karthikNaga6232** [comment]
can you please direct me to the process or give me some documentation so that i can use it to embed it into my app ?
