### ISSUE TITLE
MFA not working

### ISSUE THREAD

**Issue by manthanlal** [okta/samples-ios#77]
I ran the ios-sample code in the custom-sign in, and I was able to pass the authentication page but, the MFA didn't show up after that.

I have activated the MFA from my application settings in OKTA.

The MFA part is not linked I guess, can anyone help me out.

**Comment by IldarAbdullin-okta** [comment]
Hi @manthanlal ,

Sorry for late response. Were you able to setup MFA for your account?

Ildar
