### ISSUE TITLE
Unable to get Any callback after successful login

### ISSUE THREAD

**Issue by cnfuzedRk62** [okta/samples-ios#78]
Hi team I used OktaBrowser sign in , in my iOS App, After all setup and configuration setup , I just created a project and working everything fine. When I tried to hit signing okta function I am successfully opened login browser of okta after enter Valid credentials on hitting sign in button , That browser screen dismissed, After that no method will called , nothing will happening in my app, I am unable to get any kind of response callback please help me, i am using Swift 5. Why I am not getting any kind of Response? Here is my code when I tried to hit login button in my App.

    oktaOidc.signInWithBrowser(from: self, callback: { [weak self] stateManager, error in
            if let error = error {
                let alert = UIAlertController(title: "Error", message: error.localizedDescription, preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
                self?.present(alert, animated: true, completion: nil)
                return
            }
           
            print(stateManager?.accessToken)
            print(stateManager?.idToken)

        })
Here is my configuration File:-

```
<dict>
	<key>issuer</key>
	<string>https://dev-361749.okta.com/oauth2/default</string>
	<key>clientId</key>
	<string>0oa965jlgXlveiCvk4x6</string>
	<key>redirectUri</key>
	<string>com.GetHowNow:/callback</string>
    <key>logoutRedirectUri</key>
       <string>com.GetHowNowLogout:/callback</string>
	<key>scopes</key>
	<string>openid profile offline_access</string>
</dict>
```

**Comment by IldarAbdullin-okta** [comment]
Replied you in OIDC repo
