### ISSUE TITLE
Sign Out shows incorrect system dialog

### ISSUE THREAD

**Issue by jasmineelamblakatt** [okta/samples-ios#80]
I am using **oktaOidc?.signOutOfOkta** function to Sign out the user, on calling the function it opens the dialog with the message as "App wants to Use "oktapreview.com" to Sign In "
and on continue it takes to the browser.
This message is misleading as the user wants to Logout but "Sign In" message is shown.
Is there any way to eliminate this dialog?

Or is there any other way to perform logout? I tried clearing access token, Idtoken, and refresh token by calling revoke API, but the session is not cleared coming again to browser it automatically logs in.
<img width="246" alt="Screenshot 2020-04-30 at 12 34 22 PM" src="https://user-images.githubusercontent.com/14106534/80681768-f2da7f80-8ade-11ea-821e-bdfd80b6c146.png">

**Comment by IldarAbdullin-okta** [comment]
Answered in oidc repo - https://github.com/okta/okta-oidc-ios/issues/224
