### ISSUE TITLE
Biometric Storage Error

### ISSUE THREAD

**Issue by fxmarquand** [okta/samples-ios#81]
Hello,

When trying to bring up the browser-sign-in-and-biometric-storage, the following error pops up immediately:
![image](https://user-images.githubusercontent.com/64003046/82073767-fcb4d300-96d9-11ea-86e1-dfe5c53734ea.png)

It is possible to log in with user/password. Once logged, trying to click on the Tokens button leads to the same error popup.

The error is generated at OktaSecureStorage.getData(key:biometricPrompt:accessGroup:) at samples-ios/browser-sign-in-and-biometric-storage/Pods/OktaStorage/Sources/OktaSecureStorage.swift:207

pods.lock:
```
PODS:
  - OktaOidc (3.7.0):
    - OktaOidc/AppAuth (= 3.7.0)
    - OktaOidc/Okta (= 3.7.0)
  - OktaOidc/AppAuth (3.7.0)
  - OktaOidc/Okta (3.7.0):
    - OktaOidc/AppAuth
    - OktaOidc/Okta/Classes (= 3.7.0)
  - OktaOidc/Okta/Classes (3.7.0):
    - OktaOidc/AppAuth
  - OktaStorage (1.1.0)

DEPENDENCIES:
  - OktaOidc
  - OktaStorage

SPEC REPOS:
  trunk:
    - OktaOidc
    - OktaStorage

SPEC CHECKSUMS:
  OktaOidc: 646773483d04de414575fd7845345fb151c0c388
  OktaStorage: ae9516bf0c1d864cb36610921490f25ab57580aa

PODFILE CHECKSUM: fcf3dd32c0050c2b0d1a780e327db32ec383b114

COCOAPODS: 1.9.1
```
I've tried downgrading OktaOidc and OktaStorage in case the recent updates would cause the issue, but no luck (3.5.2 and 1.0.0).
The error is reproduced on multiple simulated devices (iPad and iPhones). I made sure TouchID was enrolled.

Xcode: Version 11.4.1 (11E503a)

Did I miss anything obvious? 

I'd be happy to provide more info as needed. Thank you for your help.

**Comment by IldarAbdullin-okta** [comment]
Hi @fxmarquand ,

Unfortunately this sample app can't work properly on simulators. The reason is the keychain that fails all biometric related queries. Keychain can't work with the simulated biometric.

Ildar

**Comment by fxmarquand** [comment]
Thank you for your quick reply!
