### ISSUE TITLE
custom-sign-in example not retrieving tokens?

### ISSUE THREAD

**Issue by bdruth** [okta/samples-ios#87]
Just trying to baseline get the custom-sign-in example working, after finding that the browser-sign-in flow is probably not going to meet my needs. browser-sign-in flow _is_ working with my setup, and I can get the custom-sign-in flow to authenticate, but then it's unable to retrieve tokens and I'm not sure why? 

The error that's pretty well buried is simply `Authorization Error: Unexpected response format while retrieving authorization code.`

I've messed with switching the `issuer` URL (as well as the `urlString` in the `SignInViewController`) between `"https://dev-xxxxxx.okta.com/oauth2/default"` and `"https://dev-xxxxxx.okta.com/"` - no difference in behavior. The `stateManager` is *nil* when the callback for `oidcClient.authenticate(withSessionToken:...)` is invoked. 

![image](https://user-images.githubusercontent.com/444571/103424005-9d73d800-4b6f-11eb-93b1-3069ef5d9554.png)

**Comment by oleggnidets-okta** [comment]
Hi @bdruth,
Apologies for late response.

Have you fixed the issue? What is your app configuration in Admin panel?

**Comment by programmarchy** [comment]
@oleggnidets-okta I have this issue, too.

Related: https://github.com/okta/okta-oidc-ios/issues/285

**Comment by oleggnidets-okta** [comment]
Closing this issue to not keep duplicates across repos. 
Thanks for reporting!
