### ISSUE TITLE
OktaError does not conform

### ISSUE THREAD

**Issue by Allen-Vantaca** [okta/samples-ios#96]
CustomAuthResponseHandler throws three fatal errors, all similar:

Line 25: `throw OktaError.invalidResponse`

Swift Compiler Error 
_Thrown expression type '(String) -> OktaError' does not conform to 'Error'_

Similar for OktaError references on line 30 and 32. 

System:
MacOS 12.2
Xcode 13.2.1
Simulator, iOS 15.2
Target iOS Version, Swift Language version left to default
Error also occurs when project is auto-converted to Swift 5 and target is updated to iOS 13.0

**Comment by arvindkrishnakumar-okta** [comment]
@Allen-Vantaca Thanks for posting!

@mikenachbaur-okta can you help with this?

**Comment by mikenachbaur-okta** [comment]
Thank you for bringing this to our attention @Allen-Vantaca, I've created a PR #97 to fix this issue.

**Comment by mikenachbaur-okta** [comment]
The above PR has been merged, so I'm going to close this issue.
